"""
RevenueIQ AI - Groq LLM Insight Generator
Automated business intelligence using AI
"""

import os
from dotenv import load_dotenv
from groq import Groq
import pandas as pd
import duckdb
import json

# Load environment variables
load_dotenv()

print("=" * 70)
print("REVENUEIQ - AI INSIGHT GENERATOR")
print("Powered by Groq LLM 🤖")
print("=" * 70)


class InsightGenerator:
    """Generate natural language insights using Groq LLM"""
    
    def __init__(self, db_path='data/revenueiq.db'):
        """Initialize Groq client and database connection"""
        self.client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        self.model = "llama-3.3-70b-versatile"
        self.db_path = db_path
        print(f"\n✓ Groq LLM initialized (Model: {self.model})")
        print(f"✓ Database: {db_path}")
    
    def _query_database(self, query):
        """Execute SQL query and return results"""
        con = duckdb.connect(self.db_path)
        result = con.execute(query).df()
        con.close()
        return result
    
    def _call_llm(self, system_prompt, user_prompt, temperature=0.7, max_tokens=2000):
        """Call Groq LLM with prompts"""
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=temperature,
            max_tokens=max_tokens
        )
        return response.choices[0].message.content
    
    def generate_executive_summary(self):
        """Generate comprehensive executive summary"""
        print("\n📊 Generating Executive Summary...")
        print("-" * 70)
        
        # Get data from database
        revenue_query = """
            SELECT 
                COUNT(DISTINCT InvoiceNo) as total_orders,
                COUNT(DISTINCT CustomerID) as total_customers,
                SUM(TotalPrice) as total_revenue,
                AVG(TotalPrice) as avg_transaction
            FROM transactions
        """
        revenue_data = self._query_database(revenue_query)
        
        cluster_query = """
            SELECT 
                ClusterName,
                COUNT(*) as customers,
                SUM(MonetaryValue) as revenue,
                AVG(MonetaryValue) as avg_value,
                AVG(Recency) as avg_recency,
                AVG(Frequency) as avg_frequency
            FROM customer_clusters
            GROUP BY ClusterName
            ORDER BY revenue DESC
        """
        cluster_data = self._query_database(cluster_query)
        
        # Prepare data summary
        data_summary = f"""
BUSINESS METRICS:
- Total Revenue: ${revenue_data['total_revenue'].iloc[0]:,.2f}
- Total Orders: {revenue_data['total_orders'].iloc[0]:,}
- Total Customers: {revenue_data['total_customers'].iloc[0]:,}
- Average Transaction: ${revenue_data['avg_transaction'].iloc[0]:,.2f}

CUSTOMER SEGMENTS:
{cluster_data.to_string(index=False)}
"""
        
        # System prompt
        system_prompt = """You are a senior business analyst specializing in retail analytics and customer intelligence. 
Your role is to transform data into actionable executive insights. 
Write in a clear, professional tone suitable for C-level executives. 
Focus on business impact and specific recommendations."""
        
        # User prompt
        user_prompt = f"""Analyze this e-commerce business data and generate a comprehensive executive summary:

{data_summary}

Please provide:
1. OVERVIEW: 2-3 sentence business performance summary
2. KEY FINDINGS: Top 3-4 critical insights from the data
3. CUSTOMER INSIGHTS: Analysis of each segment and their value
4. RISKS: Top 2-3 business risks identified
5. OPPORTUNITIES: Top 3 growth opportunities
6. RECOMMENDATIONS: 3-5 specific, prioritized action items with expected impact

Keep it concise (500-700 words), data-driven, and actionable. Use specific numbers from the data."""
        
        # Generate insight
        summary = self._call_llm(system_prompt, user_prompt, temperature=0.5, max_tokens=2500)
        
        print("\n✅ Executive Summary Generated!\n")
        print("=" * 70)
        print(summary)
        print("=" * 70)
        
        # Save to file
        with open('outputs/executive_summary.txt', 'w') as f:
            f.write("REVENUEIQ - EXECUTIVE SUMMARY\n")
            f.write("Generated by AI (Groq LLM)\n")
            f.write("=" * 70 + "\n\n")
            f.write(summary)
        
        print("\n✓ Saved to: outputs/executive_summary.txt")
        
        return summary
    
    def explain_customer_segments(self):
        """Generate detailed customer personas for each segment"""
        print("\n👥 Generating Customer Segment Personas...")
        print("-" * 70)
        
        # Get cluster details
        cluster_query = """
            SELECT 
                ClusterName,
                COUNT(*) as customer_count,
                ROUND(AVG(MonetaryValue), 2) as avg_lifetime_value,
                ROUND(AVG(Frequency), 1) as avg_orders,
                ROUND(AVG(Recency), 0) as avg_days_since_purchase,
                ROUND(AVG(AvgOrderValue), 2) as avg_order_size,
                ROUND(SUM(MonetaryValue), 2) as total_revenue
            FROM customer_clusters
            GROUP BY ClusterName
            ORDER BY total_revenue DESC
        """
        cluster_data = self._query_database(cluster_query)
        
        system_prompt = """You are a customer experience strategist and marketing expert. 
Create detailed, actionable customer personas that marketing and sales teams can use immediately. 
Be specific about behaviors, motivations, and recommended strategies."""
        
        user_prompt = f"""Based on this customer segmentation data, create detailed personas for each segment:

{cluster_data.to_string(index=False)}

For each segment, provide:
1. PERSONA NAME & DESCRIPTION: Who they are in business terms
2. CHARACTERISTICS: Key behavioral traits and metrics
3. MOTIVATIONS: Why they buy and what drives their decisions
4. PAIN POINTS: Their challenges and concerns
5. MARKETING STRATEGY: Specific tactics to engage them
6. REVENUE OPPORTUNITY: Growth potential and retention strategy

Make it practical and immediately actionable. Use bullet points for clarity."""
        
        personas = self._call_llm(system_prompt, user_prompt, temperature=0.6, max_tokens=3000)
        
        print("\n✅ Customer Personas Generated!\n")
        print("=" * 70)
        print(personas)
        print("=" * 70)
        
        # Save to file
        with open('outputs/customer_personas.txt', 'w') as f:
            f.write("REVENUEIQ - CUSTOMER SEGMENT PERSONAS\n")
            f.write("Generated by AI (Groq LLM)\n")
            f.write("=" * 70 + "\n\n")
            f.write(personas)
        
        print("\n✓ Saved to: outputs/customer_personas.txt")
        
        return personas
    
    def explain_anomalies(self):
        """Generate explanations for detected anomalies"""
        print("\n🚨 Analyzing Anomaly Detection Results...")
        print("-" * 70)
        
        # Get anomaly stats from saved file
        anomaly_summary = """
ANOMALY DETECTION SUMMARY:
- Total Transactions Analyzed: 524,874
- Anomalies Detected: 5,249 (1.00%)
- Average Anomaly Quantity: 230 units (vs normal 8 units)
- Average Anomaly Price: $489.67 (vs normal $15.49)

Pattern: Anomalies are transactions with unusually high quantities or prices
compared to the normal distribution.
"""
        
        system_prompt = """You are a fraud analyst and business operations expert. 
Analyze anomalies in transaction data and provide clear explanations of what they mean 
and what actions should be taken. Balance between fraud detection and legitimate business patterns."""
        
        user_prompt = f"""Analyze these anomaly detection results and explain:

{anomaly_summary}

Provide:
1. WHAT ARE THESE ANOMALIES: Likely explanations (fraud vs legitimate patterns)
2. BUSINESS IMPACT: Risk assessment and revenue implications
3. LEGITIMATE SCENARIOS: When high quantities/prices are normal (B2B, wholesale, etc.)
4. RED FLAGS: Warning signs of actual fraud or data errors
5. RECOMMENDED ACTIONS: Specific steps to investigate and address
6. PREVENTION: How to handle these patterns going forward

Be practical and help the team understand what to do with these findings."""
        
        explanation = self._call_llm(system_prompt, user_prompt, temperature=0.5, max_tokens=2000)
        
        print("\n✅ Anomaly Analysis Generated!\n")
        print("=" * 70)
        print(explanation)
        print("=" * 70)
        
        # Save to file
        with open('outputs/anomaly_explanation.txt', 'w') as f:
            f.write("REVENUEIQ - ANOMALY ANALYSIS\n")
            f.write("Generated by AI (Groq LLM)\n")
            f.write("=" * 70 + "\n\n")
            f.write(explanation)
        
        print("\n✓ Saved to: outputs/anomaly_explanation.txt")
        
        return explanation
    
    def generate_forecast_commentary(self):
        """Generate natural language commentary on sales forecast"""
        print("\n📈 Generating Forecast Commentary...")
        print("-" * 70)
        
        forecast_data = """
SALES FORECAST - NEXT 30 DAYS:
- Predicted Revenue: $1,612,322.91
- Daily Average: $53,744.10
- Model: Exponential Smoothing with Seasonality
- Confidence Level: Moderate (historical patterns show variability)

HISTORICAL CONTEXT:
- Previous Month Revenue: ~$462K (December partial)
- Best Month: November 2011 ($1.45M)
- Worst Month: February 2011 ($497K)
- Average Month: $885K

CURRENT TRENDS:
- Customer Retention: 20.6% (low)
- At-Risk Customers: 978 (could impact forecast)
- VIP Concentration: 18 customers = 20.9% of revenue
"""
        
        system_prompt = """You are a revenue forecasting expert and CFO advisor. 
Translate predictive model outputs into strategic business commentary that helps 
leadership make informed decisions. Focus on risks, opportunities, and action items."""
        
        user_prompt = f"""Analyze this sales forecast and provide strategic commentary:

{forecast_data}

Provide:
1. FORECAST INTERPRETATION: What the $1.61M prediction means in context
2. CONFIDENCE ASSESSMENT: How reliable is this forecast and why
3. RISK FACTORS: What could cause us to miss the target
4. UPSIDE POTENTIAL: What could drive us to exceed the forecast
5. STRATEGIC RECOMMENDATIONS: Specific actions to hit/exceed the target
6. CONTINGENCY PLANNING: What to prepare for if forecast is off

Be specific about dollar impacts and timeline for actions."""
        
        commentary = self._call_llm(system_prompt, user_prompt, temperature=0.6, max_tokens=2000)
        
        print("\n✅ Forecast Commentary Generated!\n")
        print("=" * 70)
        print(commentary)
        print("=" * 70)
        
        # Save to file
        with open('outputs/forecast_commentary.txt', 'w') as f:
            f.write("REVENUEIQ - FORECAST COMMENTARY\n")
            f.write("Generated by AI (Groq LLM)\n")
            f.write("=" * 70 + "\n\n")
            f.write(commentary)
        
        print("\n✓ Saved to: outputs/forecast_commentary.txt")
        
        return commentary
    
    def generate_churn_insights(self):
        """Generate insights about customer churn"""
        print("\n⚠️  Generating Churn Analysis Insights...")
        print("-" * 70)
        
        churn_data = """
CUSTOMER CHURN ANALYSIS:
- Total Customers: 4,320
- Active Customers: 2,894 (67%)
- Churned Customers: 1,445 (33.3%)
- At-Risk (>150 days inactive): 978 customers

CHURN PREDICTION MODEL:
- Accuracy: 100% (perfect classification)
- Top Predictor: Recency (81% importance)
- Pattern: 90+ days without purchase = high churn risk

REVENUE IMPACT:
- Lost Revenue from Churned: ~$480K annually
- At-Risk Revenue: $451K
- Recovery Opportunity: 20-30% win-back rate possible
"""
        
        system_prompt = """You are a customer retention specialist and CRM strategist. 
Provide actionable insights on reducing churn and winning back lost customers. 
Focus on practical, implementable strategies."""
        
        user_prompt = f"""Analyze this churn data and provide retention strategy:

{churn_data}

Provide:
1. CHURN ANALYSIS: What the 33.3% churn rate means and industry context
2. ROOT CAUSES: Likely reasons customers are leaving
3. WIN-BACK STRATEGY: Specific campaigns to recover churned customers
4. PREVENTION TACTICS: How to stop future churn (focus on 90-day mark)
5. PRIORITIZATION: Which churned customers to target first
6. EXPECTED OUTCOMES: Realistic recovery rates and revenue impact

Include specific timelines and budget recommendations if applicable."""
        
        insights = self._call_llm(system_prompt, user_prompt, temperature=0.6, max_tokens=2000)
        
        print("\n✅ Churn Insights Generated!\n")
        print("=" * 70)
        print(insights)
        print("=" * 70)
        
        # Save to file
        with open('outputs/churn_insights.txt', 'w') as f:
            f.write("REVENUEIQ - CHURN ANALYSIS & RETENTION STRATEGY\n")
            f.write("Generated by AI (Groq LLM)\n")
            f.write("=" * 70 + "\n\n")
            f.write(insights)
        
        print("\n✓ Saved to: outputs/churn_insights.txt")
        
        return insights
    
    def generate_all_insights(self):
        """Generate all insights in one go"""
        print("\n" + "=" * 70)
        print("GENERATING COMPLETE AI INSIGHT REPORT")
        print("=" * 70)
        
        insights = {
            'executive_summary': self.generate_executive_summary(),
            'customer_personas': self.explain_customer_segments(),
            'forecast_commentary': self.generate_forecast_commentary(),
            'anomaly_analysis': self.explain_anomalies(),
            'churn_insights': self.generate_churn_insights()
        }
        
        print("\n" + "=" * 70)
        print("✅ ALL AI INSIGHTS GENERATED!")
        print("=" * 70)
        print("\n📁 Generated Files:")
        print("   - outputs/executive_summary.txt")
        print("   - outputs/customer_personas.txt")
        print("   - outputs/forecast_commentary.txt")
        print("   - outputs/anomaly_explanation.txt")
        print("   - outputs/churn_insights.txt")
        
        print("\n🎉 AI-Powered Business Intelligence Complete!")
        print("\nThese insights are ready to share with stakeholders!")
        
        return insights


def main():
    """Execute AI insight generation pipeline"""
    
    # Initialize
    generator = InsightGenerator()
    
    # Generate all insights
    insights = generator.generate_all_insights()
    
    print("\n✨ RevenueIQ AI Analysis Complete!")
    print("\n🎯 CORE PROJECT: 100% COMPLETE!")
    print("\nNext: Polish documentation and prepare for portfolio!")


if __name__ == "__main__":
    main()
